### ISSUE TITLE
Detailed install instructions of tested platform (linux/mac/windows), python3 version (anaconda?, 3.5, 3.6?), pytorch version

### ISSUE THREAD

**Issue by erwincoumans** [locuslab/lcp-physics#1]
I'm getting errors after installing it, see below. Can you describe on what platform you develop and test lcp-physics, which versions of all relevant packages (Linux distro, mac, windows etc), python3 version (anaconda?) etc.

Never mind, using anaconda works.
~~~~~

conda install pytorch torchvision -c pytorch
pip3 install pygame
python3 setup.py develop
cd demos
python3 demo.py
~~~~~

![image](https://user-images.githubusercontent.com/725468/34268277-f5de7372-e634-11e7-9db3-3edcefa32d7a.png)

erwincoumans-macbookpro2:demos erwincoumans$ python inference_demo.py 
  10 / 11  30.0Traceback (most recent call last):
  File "inference_demo.py", line 248, in <module>
    inference_demo(screen)
  File "inference_demo.py", line 49, in inference_demo
    grad = c.mass.grad.data
AttributeError: 'NoneType' object has no attribute 'data'

**Comment by belbs** [comment]
I had introduced a small bug on the inference script, should be fixed right now. (Currently testing here.)

**Comment by belbs** [comment]
Regarding demo running slowly, for simple examples like that, most of that is simply because the pygame display is not really optimized, if you run with no display (python demo.py -nd or setting screen=None in the run_world code) it should run much faster than real time. On top of that, especially for more complex examples, the solver is still running on dense matrices, so we're currently working on speeding that up taking advantage of the sparsity in the formulation.

**Comment by erwincoumans** [comment]
Thanks for the quick reply, performance makes sense now. After updating, the error is as follows:

~~~~~~~
[torch.DoubleTensor of size 1]

Traceback (most recent call last):
  File "inference_demo.py", line 247, in <module>
    inference_demo(screen)
  File "inference_demo.py", line 71, in inference_demo
    rec = Recorder(DT, screen)
  File "/Users/erwincoumans/dev/lcp-physics/lcp_physics/physics/utils.py", line 58, in __init__
    os.mkdir(path)
FileNotFoundError: [Errno 2] No such file or directory: 'videos/frames'
~~~~~~~

**Comment by belbs** [comment]
Fixed. Strange that it passed the tests, I'll check on that.
